games = {
"rb": {"any% glitchless": "World record for Pokémon Red/Blue (any% glitchless): 1:50 (IGT) by ExarionU (http://goo.gl/ZWsjAj).",
       "151 pokemon": "World record for Pokémon Red/Blue (151 pokemon): 2:23:22 (RTA) by SheNanagans_ (http://goo.gl/2Ozovl)."},
"y": {"any% nsc": "World record for Pokémon Yellow (any% nsc): 57:54 (RTA) by SheNanagans_ (http://goo.gl/PX3MKO).",
      "any% glitchless": "World record for Pokémon Yellow (any% glitchless): 1:56 (IGT) by Gunnermaniac3 ()."},
"gs": {"any%": "World record for Pokémon Gold/Silver (any%): 43:47 (RTA) by Werster (http://goo.gl/f5Nxvv).",
       "any% glitchless": "World record for Pokémon Gold/Silver (any% glitchless): 3:24 (IGT) by Werster (http://goo.gl/Jh1yME)."},
"c": {"any% glitchless": "World record for Pokémon Crystal (any% glitchless): 3:22 (IGT) by Werster (http://goo.gl/CckKE0)."},
"rs": {"any% glitchless": "World record for Pokémon Ruby/Sapphire (any% glitchless): 2:10:53 (IGT) by Gunnermanic3 (http://goo.gl/wPC4mV)."},
"e": {"any%": "World record for Pokémon Emerald (any%): 2:04:07 (RTA) by Werster (http://goo.gl/s0ksyN).",
      "any% glitchless": "World record for Pokémon Emerald (any% glitchless): 2:42:55 (IGT) by Roushmore917 (http://goo.gl/oeZPg7)."},
"frlg": {"any% glitchless": "World record for Pokémon FireRed/LeafGreen (any% glitchless): 2:05:24 (IGT) by Werster (http://goo.gl/6rufkq).",
         "Round 2": "World record for Pokémon FireRed/LeafGreen (Round 2): 3:43 (IGT) by Werster (http://goo.gl/Ua4aOm)."},
"col": {"any%": "World record for Pokémon Colosseum (any%): 4:16 (IGT) by FlareRDB (http://goo.gl/hqJrlk)."},
"xd":  {"any%": "World record for Pokémon XD: Gale of Darkness (any%): 4:54 (IGT) by LBlueEagle (http://goo.gl/CsO51m)."},
"dp": {"any%": "World record for Pokémon Diamond/Pearl(any%): 1:05:32 (RTA) by Pokefluke (http://goo.gl/wOlXCG).",
       "any% glitchless": "World record for Pokémon Diamond/Pearl (any% glitchless): 3:56 (IGT) by GarfieldTheLightning (http://goo.gl/o7PU7A)."},
"pt": {"any% glitchless": "World record for Pokémon Platinum (any% glitchless): 3:59 (IGT) by MoneyHypeMike (http://goo.gl/Z4LfOK)."},
"hgss": {"any%": "World record for Pokémon HeartGold/SoulSilver (any%): 2:20:20 (RTA) by Werster (http://goo.gl/LHpp44).",
         "any% glitchless": "World record for Pokémon HeartGold/SoulSilver (any% glitchless): 3:56 (IGT) by Werster (http://goo.gl/y9bZ4a)."},
"bw": {"any% glitchless": "World record for Pokémon Black/White (any% glitchless): 3:27 (IGT) Vulajin (http://goo.gl/M5X4YS)."},
"b2w2": {"any% glitchless": "World record for Pokémon Black2/White2 (any% glitchless): 3:25 (IGT) by GarfieldTheLighning (http://goo.gl/uAXsLN)."},
"xy": {"any% glitchless": "World record for Pokémon X/Y (any% glitchless): 3:56 (IGT) by iMAX1UP (http://goo.gl/2npHW4)."}
}